<?php $api = $this->api ?>
<h2>Documentation</h2>

<h4><?php echo $this->escapeHtml($api->getName()) ?> (v<?php echo $this->escapeHtml($api->getVersion()) ?>)</h4>

<div class="row">
    <aside class="col-md-3" role="nav">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="<?php echo $this->url('zf-apigility/documentation', array('api' => null, 'version' => null)) ?>">API List</a></li>
        </ul>
    </aside>

    <main class="col-md-9 panel-group" role="main" id="docs-accordion">
    <?php foreach ($api->getServices() as $service) {
        echo $this->render('zf-apigility-documentation/service', array('service' => $service, 'embedded' => true));
    } ?>
    </main>
</div>
